version: "3"

services:
  standalone:
    image: apachepulsar/pulsar:2.7.1
    ports:
      - "6650:6650"
      - "8080:8080"
    environment:
      - BOOKIE_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
      - PULSAR_PREFIX_transactionCoordinatorEnabled=true
    command: >
      /bin/bash -c "
      bin/apply-config-from-env.py conf/standalone.conf
      && (bin/pulsar initialize-transaction-coordinator-metadata -cs 127.0.0.1:2181 -c standalone &)
      && bin/pulsar standalone --advertised-address standalone
      "

  dashboard:
    profiles: ["dashboard"]
    image: apachepulsar/pulsar-dashboard
    depends_on:
      - standalone
    ports:
      - "80:80"
    environment:
      - SERVICE_URL=http://standalone:8080
